src/Entity/Beer.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BeerRepository")
 */
class Beer
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $degre;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\BeerType", inversedBy="beers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $beer_type;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="beers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $producer;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="beer", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDegre(): ?float
    {
        return $this->degre;
    }

    public function setDegre(float $degre): self
    {
        $this->degre = $degre;

        return $this;
    }

    public function getBeerType(): ?BeerType
    {
        return $this->beer_type;
    }

    public function setBeerType(?BeerType $beer_type): self
    {
        $this->beer_type = $beer_type;

        return $this;
    }

    public function getProducer(): ?User
    {
        return $this->producer;
    }

    public function setProducer(?User $producer): self
    {
        $this->producer = $producer;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setBeer($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getBeer() === $this) {
                $comment->setBeer(null);
            }
        }

        return $this;
    }
}

src/Controller/ProducerController.php
<?php

namespace App\Controller;

use App\Entity\Beer;
use App\Form\NewBeerFormType;
use App\Repository\BeerRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ProducerController extends AbstractController
{

    /**
     * @Route("/producer/beers", name="producer_beers")
     */
    public function beerList(BeerRepository $beerRepository)
    {
        $producer = $this->getUser();
        $beersProducer = $beerRepository->findBy(['producer' => $producer->getId()]);

        return $this->render('producer/beers.html.twig', [
            'beers' => $beersProducer,
        ]);
    }

    /**
     * @Route("/producer/new-beer", name="create_beer")
     */
    public function newBeer(Request $request)
    {
        $beer = new Beer();
        $form = $this->createForm(NewBeerFormType::class, $beer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $beer->setProducer($this->getUser());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($beer);
            $entityManager->flush();

            // do anything else you need here, like send an email

            return $this->redirectToRoute('producer_beers');
        }

        return $this->render('producer/new-beer.html.twig', [
            'newBeerForm' => $form->createView(),
        ]);
    }
}

templates/producer/beers.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les bières{% endblock %}

{% block body %}
    <div class="container">
        <div class="text-center">
            <h1>Les bières que je propose</h1>
        </div>
        {% if beers %}
        <table class="table table-hover table-striped table-bordered">
            <thead>
            <tr>
                <th class="col-10" scope="col">Nom</th>
                <th class="col-2">Prix</th>
            </tr>
            </thead>
            <tbody>
            {% for beer in beers %}
                <tr style="cursor:pointer" onclick="window.location='{{ path("beer_show", {"id":beer.id}) }}'">
                    <td class="col-10">{{ beer.name }}</td>
                    <td class="col-2"> {{ beer.price }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
            <div class="text-center">
                <p>Vous ne proposez actuellement pas de bières</p>
            </div>
        {% endif %}
        <div class="text-center">
            <a class="btn btn-primary" href="{{ path('create_beer') }}">Créer un type de bière</a>
        </div>
    </div>

{% endblock %}

templates/producer/new-beer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un nouveau type de bière{% endblock %}

{% block body %}
    <div class="text-center">
        <h1>Ajouter une bière</h1>
    </div>
    <div class="container">
        {{ form_start(newBeerForm) }}
        {{ form_row(newBeerForm.name, {'label': 'Nom de la bière', 'attr': {'placeholder': 'Nom de la bière' }}) }}
        {{ form_row(newBeerForm.img, {'label': 'Image'}) }}
        {{ form_row(newBeerForm.degre, {'label': '% alcool', 'attr': {'placeholder': '8.6' }}) }}
        {{ form_row(newBeerForm.price, {'label': 'Prix unitaire', 'attr': {'placeholder': '2.50' }}) }}
        {{ form_row(newBeerForm.beerType, {'label': 'Type'}) }}
        {{ form_row(newBeerForm.description, {'label': 'Description'}) }}

        <div class="text-center">
            <button class="btn btn-outline-primary">Ajouter la bière</button>
        </div>
        {{ form_end(newBeerForm) }}
    </div>
{% endblock %}